-type raw_position() :: {Line   :: non_neg_integer(),
                         Column :: non_neg_integer()}.
-type raw_term()   :: {atom(), raw_field()}
                    | binary().
-type raw_field()  :: {raw_term(), raw_position()}.
-type raw_config() :: [raw_field()].

-type typer_error() :: {missing, Name :: atom()}
                     | {invalid,
                        Name  :: atom(),
                        Type  :: atom(),
                        Value :: binary()}.

-type composer_error() :: {unknown_anchor, binary()}
                        | {duplicate_key, atom()}.

-type reload_type() :: sync | async.

-type ret_novalue() :: ok
                     | {error, Reason :: binary()}.

-type ret_value(T) :: {ok, T}
                    | {error, Reason :: binary()}.

-type record_spec() :: {Name :: atom(),
                        [{FieldName :: atom(),
                          Typespec :: nakaz_typespec(),
                          Default :: any()}]}.

-type record_specs() :: [record_spec()].

-define(NAKAZ_MAGIC_FUN, nakaz_magic_fun_that_should_be_autogenerated).
